import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
// import Link from 'next/link'
import Blog from '../components/Blog'

// const URL = process.env.STRAPIBASEURL
// const URL = 'http://localhost:1337'
const URL = `https://murmuring-bayou-82351.herokuapp.com`

export async function getStaticProps(context) {
  const fetchParams = {
    method: 'post',
    headers: {
      'content-type': 'application/json',
    },
    body: JSON.stringify({
      query: `{
      blogposts{
        title
        blogbody
        description
        slug
        splash{
          url
        }
      }
    }
      `,
    }),
  }

  const res = await fetch(`${URL}/graphql`, fetchParams)
  console.log('res', res)
  const { data } = await res.json()
  console.log('data', data)

  return {
    props: data,
    revalidate: 10,
  }
}

export default function Home(data) {
  console.log(data)
  // console.log(data.blogposts)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>{data.blogposts[0].title}</h1>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        {/* <div>
          {data.blogposts.map((blogpost, i) => {
            const { title, description, slug } = blogpost
            return <Blog title={title} description={description} slug={slug} key={i} />
          })}
        </div> */}

        <p className={styles.description}>
          Get started by editing <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a href="https://github.com/vercel/next.js/tree/canary/examples" className={styles.card}>
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>Instantly deploy your Next.js site to a public URL with Vercel.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
